### ISSUE TITLE
Wrong version specified in readme

### ISSUE THREAD

**Issue by nmoinvaz** [TheMrMilchmann/setup-msvc-dev#1]
It looks like the readme specifies version `v1` which throws an error on GitHub CI because it doesn't exist. So it should be `TheMrMilchmann/setup-msvc-dev@v1.0.0` instead.

**Comment by TheMrMilchmann** [comment]
Hi, do you have an example of a failing workflow? [Any git ref should be a valid version for an action.](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iduses) This includes commit hashes and, in particular, branch names. Because in my opinion, moving git tags to track the latest version is counter-intuitive and the approach is fully opaque, I decided to make [v1 a branch in this repository](https://github.com/TheMrMilchmann/setup-msvc-dev/tree/v1).

To add to that, [here](https://github.com/GW2ToolBelt/GW2ML/blob/d0fc32eaa648fa9a5b32f3a9beba850b3823b291/.github/workflows/ci.yml#L14) is an example where the action is used that way.

**Comment by nmoinvaz** [comment]
This is what I get in GitHub CI:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/1364432/163683821-e99da6bd-0c55-46fc-ad62-fa2f6d084021.png">

Using v1.0.0 works.

**Comment by nmoinvaz** [comment]
Actually it looks like it is just misspelled. `mvsc` should be `msvc`.

**Comment by TheMrMilchmann** [comment]
Right. Even the title of the readme is. Thanks for pointing this out.

**Comment by nmoinvaz** [comment]
I thought it was due to the version because when I went to the GH marketplace it gave me the full version.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/1364432/163683908-28d09fb0-cbf0-4eef-
9b83-7fbc69f30ee5.png">

**Comment by nmoinvaz** [comment]
Thanks for the nice GitHub action!
